### ISSUE TITLE
cannot load 32-bit SWT libraries on 64-bit JVM

### ISSUE THREAD

**Issue by sha198989** [SpiderLabs/deface#6]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at com.trustwave.deface.gui.DefaceGUI.showWindow(Unknown Source)
	at com.trustwave.deface.Deface.main(Unknown Source)

**Comment by bhaveshsingh89** [comment]
On 64-bit JVM's you need the 64-bit SWT. Current versions can be downloaded here:
Note the first two downloads, the first is for x32, the other for x64.
[http://archive.eclipse.org/eclipse/downloads/drops/R-3.6.1-201009090800/index.php#SWT](url)

Note: Even on 64bit Windows, if you use the 32bit JVM, you still need the 32bit SWT version!
